log_path: saliency_log

class_name: chair
rot_exp:
  rot_train: False
  rot_test: False  # rotation experiment

network: pointnet
max_epoch: 30
rot_gravity: False
data_aug: False
iou_thresh: 0.1

data:
  data_path: data
  annot_path: annotations/all.json
  model_root: models
  pcd_root: pcds
  train_txt: splits/train.txt
  val_txt: splits/val.txt

hydra:
  run:
    dir: ${log_path}/${class_name}/${rot_exp}/${network}
  sweep:
    dir: ${log_path}
    subdir: ${class_name}/${rot_exp}/${network}