log_path: saliency_log

class_name: chair
rot_exp:
  rot_train: True
  rot_test: True  # rotation experiment

network: rsnet
rot_gravity: False
data_aug: False

iou_thresh: 0.1

data:
  data_path: data
  annot_path: annotations/all.json
  model_root: models
  pcd_root: pcds
  test_txt: splits/test.txt

hydra:
  run:
    dir: ${log_path}/${network}/${class_name}
    # dir: ${log_path}/${network}_binlog_${class_name}_geo