optimizer:
  lr: 0.001
  lr_decay: 0.5
  lr_step: 5
  weight_decay: 0.001

network: transformer
gpu: 0
batch_size: 8
max_epoch: 30
eval_step: 1
num_workers: 0
class_name: chair
log_path: correspondence_log
num_points: 2048

rot_gravity: False
rot_exp:
  rot_train: False
  rot_test: False  # rotation experiment

task: train
data:
  annot_path: annotations/all.json
  model_root: models
  pcd_root: pcds
  train_txt: splits/train.txt
  val_txt: splits/val.txt
  test_txt: splits/test.txt

hydra:
  run:
    dir: ${log_path}/${class_name}/${rot_exp}/${network}
  sweep:
    dir: ${log_path}
    subdir: ${class_name}/${rot_exp}/${network}