optimizer:
  lr: 0.001
  lr_decay: 0.5
  lr_step: 500
  weight_decay: 0.001

network: pointnet
gpu: 0
batch_size: 8
max_epoch: 100
eval_step: 1
num_workers: 0
class_name: chair
log_path: correspondence_log
num_points: 2048

rot_gravity: False
rot_exp:
  rot_train: True
  rot_test: True  # rotation experiment

task: train
data:
  annot_path: annotations/all.json
  model_root: models
  pcd_root: pcds
  train_txt: splits/train.txt
  val_txt: splits/val.txt
  test_txt: splits/test.txt

hydra:
  run:
    dir: ${log_path}/${network}/${class_name}